### PR TITLE
Add Dockerfile for bioformats2raw

### PR DESCRIPTION
**Pull request by annshress**
Add Dockerfile for bioformats2raw

Next: Setup an environment with `imod` binaries.

### CODE REVIEW

**Comment by blowekamp** [comment]
@philipmac  There are some unmaintained Docker files in the  "em_workflows/utils" directory. Should this go there as well or is a refactor needed?

**Comment by mbopfNIH** [comment]
The bioformats2raw via docker runs without errors on my M1 Mac, but I have no way to test the validity of the Zarr output.

**Review by philipmac — APPROVED** [review]

**Comment by mbopfNIH** [comment]
Using WGET makes this Dockerfile more self-contained, but will require a longer start-up time. Is there a way to just run `bioformats2raw` once the container has been created?

**Comment by annshress** [comment]
@mbopfNIH 
COPY or RUN will only affect the docker image building time. It replaces the manual hassle of downloading the binary.
Once the image is built, container will have `bioformats2raw` binary available.

Eventually, the base image should be changed to `rocky` to somewhat replicate the remote server.

**Comment by annshress** [comment]
Closing this branch, as `docker` branch (https://github.com/niaid/image_portal_workflows/pull/284) has been merged which contains this commit.

**Pull request closed without merging**
