### PR TITLE
bump n2 version

### PR DESCRIPTION
**Pull request by philipmac**
bump to prefect 2.18.1 to test updated FE

### CODE REVIEW

**Comment by annshress** [comment]
Prefect server is at different version: https://github.com/niaid/tf-hedwig-workflow-api/blob/main/Dockerfile

**Review by annshress — CHANGES_REQUESTED** [review]
Prefect server is at different version: https://github.com/niaid/tf-hedwig-workflow-api/blob/main/Dockerfile

Also, there's another PR that matches. https://github.com/niaid/image_portal_workflows/pull/467

As long as versions in either repo is same, we are good.

**Comment by philipmac** [comment]
> Prefect server is at different version: https://github.com/niaid/tf-hedwig-workflow-api/blob/main/Dockerfile
> 
> Also, there's another PR that matches. #467
> 
> As long as versions in both repo are the same, we are good.

I think the other PR is to version 2.16 - this is to 2.8
The current dev is running 2.18 - deployed last night, tested. This is was to test matching versions on HPC

**Comment by philipmac** [comment]
bumping to 2.19.1 instead - matching
https://github.com/niaid/tf-hedwig-workflow-api/commit/3ab8746198ca4766cfd4f61b435880c10b18dce8

**Pull request merged**
